# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widgetCamera = QtWidgets.QWidget(self.centralwidget)
        self.widgetCamera.setGeometry(QtCore.QRect(10, 0, 781, 481))
        self.widgetCamera.setObjectName("widgetCamera")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(210, 499, 351, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.yogbox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.yogbox.setObjectName("yogbox")
        self.yogbox.addItem("")
        self.yogbox.addItem("")
        self.horizontalLayout.addWidget(self.yogbox)
        self.btnToggle = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnToggle.setObjectName("btnToggle")
        self.horizontalLayout.addWidget(self.btnToggle)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.yogbox.setItemText(0, _translate("MainWindow", "Yolo"))
        self.yogbox.setItemText(1, _translate("MainWindow", "Hog"))
        self.btnToggle.setText(_translate("MainWindow", "Capture !"))
